/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "VRef_1V2_aliases.h"
#include "VRef_1V2.h"
#include "Clock_1.h"
#include "PWM_1.h"
#include "MDIO_M_aliases.h"
#include "MDIO_M.h"
#include "VDAC8_1.h"
#include "Opamp_1.h"
#include "MDC_M_aliases.h"
#include "MDC_M.h"
#include "LED_2_aliases.h"
#include "LED_2.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "Clock_2.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "LCD.h"
#include "PWM_2.h"
#include "MDIO_host_2_my.h"
#include "ISR.h"
#include "interrupt_MDIO_aliases.h"
#include "interrupt_MDIO.h"
#include "Debug_MDIO_aliases.h"
#include "Debug_MDIO.h"
#include "LED_3_aliases.h"
#include "LED_3.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

